/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SmartProRouteImport } from './routes/smart-pro'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as QuotationRouteImport } from './routes/quotation'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'

const SmartProRoute = SmartProRouteImport.update({
  id: '/smart-pro',
  path: '/smart-pro',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotationRoute = QuotationRouteImport.update({
  id: '/quotation',
  path: '/quotation',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/partners': typeof PartnersRoute
  '/quotation': typeof QuotationRoute
  '/services': typeof ServicesRoute
  '/smart-pro': typeof SmartProRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/partners': typeof PartnersRoute
  '/quotation': typeof QuotationRoute
  '/services': typeof ServicesRoute
  '/smart-pro': typeof SmartProRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/partners': typeof PartnersRoute
  '/quotation': typeof QuotationRoute
  '/services': typeof ServicesRoute
  '/smart-pro': typeof SmartProRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/partners'
    | '/quotation'
    | '/services'
    | '/smart-pro'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/contact' | '/partners' | '/quotation' | '/services' | '/smart-pro'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/partners'
    | '/quotation'
    | '/services'
    | '/smart-pro'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  PartnersRoute: typeof PartnersRoute
  QuotationRoute: typeof QuotationRoute
  ServicesRoute: typeof ServicesRoute
  SmartProRoute: typeof SmartProRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/smart-pro': {
      id: '/smart-pro'
      path: '/smart-pro'
      fullPath: '/smart-pro'
      preLoaderRoute: typeof SmartProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotation': {
      id: '/quotation'
      path: '/quotation'
      fullPath: '/quotation'
      preLoaderRoute: typeof QuotationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  PartnersRoute: PartnersRoute,
  QuotationRoute: QuotationRoute,
  ServicesRoute: ServicesRoute,
  SmartProRoute: SmartProRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
